### ISSUE TITLE
Error while running a Go plugin

### ISSUE THREAD

**Issue by BrunoPereira** [rwynn/monstache#109]
@rwynn need your help again

I'm trying to run monstache on docker with a Go plugin and I'm getting the following **error:**
ERROR 2018/09/27 15:54:00 Plugin 'Map' function must be typed func(*monstachemap.MapperPluginInput) (*monstachemap.MapperPluginOutput, error)

The error looks pretty evident.... the thing is, my Map function is of that type.
**code sample:**
func Map(input *monstachemap.MapperPluginInput) (output *monstachemap.MapperPluginOutput, err error) {
	doc := input.Document

As you can see, I copy it from the example in the doc ( the doc is great by the way).
And to test it, I did the following:
**code:**
fmt.Printf("%T\n", plugin.Map)

**stdout:**
func(*monstachemap.MapperPluginInput) (*monstachemap.MapperPluginOutput, error)

I've checked your code and where that error is thrown (https://github.com/rwynn/monstache/blob/master/monstache.go#L1413).
What I can't find out is why.... 
What m I doing wrong????

tnx

Side Note:
I haven't checked all the Dockerfiles for the different containers, so I don't know if this is a bug or not.
The rwynn/monstache:rel3 container, on his Dockerfile, it has the fallowing line: **FROM rwynn/monstache-builder:1.0.2**
The Dockerfile used to compile the Go plugins (https://github.com/rwynn/monstache/blob/master/docker/plugin/Dockerfile) has **FROM rwynn/monstache-builder:1.0.0**

this lids to  the following **error:**
Unable to load mapper plugin /tmp/npvr-plugin.so: plugin.Open("/tmp/npvr-plugin"): plugin was built with a different version of package internal/cpu

So maybe you forgot to change the plugin/Dockerfile when you bump the version for the monstache Dockers?

**Comment by rwynn** [comment]
Thanks for reporting the issue. I just checked in a change to up the base version as you mentioned. Can you please try to rebuild the plugin after taking an update?

I think those bases are based on different versions of the Golang docker container. So hopefully that was the issue.

**Comment by BrunoPereira** [comment]
I did that even before I created the issue.
I basically cloned your code and changed that line to the appropriated version.
I "did your commit" on my local repo and carry on....

The error I report, 
ERROR 2018/09/27 15:54:00 Plugin 'Map' function must be typed func(*monstachemap.MapperPluginInput) (*monstachemap.MapperPluginOutput, error)
happened with the compiled plugin using the corrected Dockerfile

**Comment by rwynn** [comment]
Are you using the rel3 docker image?  If so are you importing from gopkg.in/rwynn/monstache.v3/monstachemap in your plugin source code?  

Sorry I’m not sure if I documented it properly for the 2 different versions.

**Comment by BrunoPereira** [comment]
I'm using the rel3 Docker image, but that's not the import I'm using.
I'm using the "github.com/rwynn/monstache/monstachemap"

The dependency in rel3 image is different???

You may have to clear that in the doc.
Maybe a sub section in the /advanced/#docker ? or a new section /advanced/#versions ?
Just to clear out the differences .

**Comment by rwynn** [comment]
Yes I will update the docs next release.

**Comment by rwynn** [comment]
And yes if you are using rel3 then you should switch to the rel3 branch in git and all package imports in plugins should ref monstache.v3 via gopkg.

**Comment by BrunoPereira** [comment]
I updated the import to "gopkg.in/rwynn/monstache.v3/monstachemap"
Some things I've experienced:

**typo when using rel3**
**Conditions:**
plugin $ git status
On branch rel3
Your branch is up-to-date with 'origin/rel3'
docker pull rwynn/monstache:rel3

**leads to:**
Step 1/6 : FROM rwynn/monstache-builder:1.0.2 AS build-app
Error parsing reference: "rwynn/monstache-builder:1.0.2 AS build-app" is not a valid repository/tag: invalid reference format

**Miss match lib** 
**Conditions:**
Edit the plugin Dockerfile to: FROM rwynn/monstache-builder:1.0.2
./build.sh <- Successfully builds the plugin
docker run -v ~/monstache/:/tmp/ rwynn/monstache:rel3 -f /tmp/config-sharded.toml -mapper-plugin-path /tmp/npvr-plugin.so

**leads to:**
ERROR 2018/09/28 15:34:35 Unable to load mapper plugin /tmp/npvr-plugin.so: plugin.Open("/tmp/npvr-plugin"): plugin was built with a different version of package gopkg.in/olivere/elastic.v5

I updated the docker images (docker pull) before invoking the commands

**Comment by BrunoPereira** [comment]
By the way, this is (part of) what I get when building the plugin:
Fetching https://gopkg.in/olivere/elastic.v5?go-get=1
Parsing meta tags from https://gopkg.in/olivere/elastic.v5?go-get=1 (status code 200)
get "gopkg.in/olivere/elastic.v5": found meta tag get.metaImport{Prefix:"gopkg.in/olivere/elastic.v5", VCS:"git", RepoRoot:"https://gopkg.in/olivere/elastic.v5"} at https://gopkg.in/olivere/elastic.v5?go-get=1
gopkg.in/olivere/elastic.v5 (download)

**Comment by rwynn** [comment]
Hi, regarding the first error `invalid reference format`.  I didn't get that on docker version `18.06.0-ce`.  What version of docker are you using?

I DID get your 2nd error.  I think it means that a code change was pushed to the elastic v5 library since the monstache:rel3 was created.  I will need to look into a fix for that.  

One way to work around this is to build everything on a linux machine.  For example use `go get gopkg.in/rwynn/monstache.v3`.  That will give you a monstache binary named monstache.v3 that you can rename to monstache. Then build your plugin locally using `go build -buildmode=plugin -o npvr-plugin.so npvr-plugin.go`.  

Finally create a docker image using the monstache binary and optionally the plugin built into the image. That should ensure that everything is on the same version of code.

**Comment by rwynn** [comment]
Another option to fix it....

cd into `monstache/docker/release` and edit the `Dockerfile` as follows:

```
FROM rwynn/monstache-builder-cache-rel3:1.0.6 AS build-app

WORKDIR /go/src/cache-app

COPY . .

RUN go get -u . // ADD this line to update depends from github

RUN make release
```

Then run `monstache/docker/release/build.sh`.  That should produce a local docker image of `rwynn/monstache:3.17.2` which should be in sync with the plugin you just built.  This worked for me.

The problem here is that the source code needs to match and these scripts are pulling live code from github.

**Comment by rwynn** [comment]
Actually, I have a third idea which doesn't involve you having to create your own containers and is the real fix that needs to be applied to the repo.  Hold tight just testing this out.

**Comment by rwynn** [comment]
So, I will be fixing this in the next release but for now you can make only these changes and then redo your plugin build and it should work.    This fix makes the plugin build use the same fixed source code embedded in the release images for monstache.  So there should not be a mismatch when you run against the released images.  I also removed the AS in Dockerfile but I think that is just maybe your version of docker is older?

Changes in `rel3` branch `docker/plugin` directory.

build.sh
```
#!/bin/bash

plugin=$(<.plugin)

# # Build a docker image
docker build --build-arg PLUGIN="$plugin" \
       -f ./Dockerfile -t monstache-plugin .

# Start a container from the newly built docker image
docker run --rm -d monstache-plugin tail -f /go/src/cache-app/$plugin.go

# Get the container id of the last created container
CONTAINER_ID=$(docker ps -l -q)


# If the folder docker-build exists locally
if [ -d docker-build ] ; then
 # Then remove it
 rm -r docker-build
fi

mkdir docker-build

docker cp "$CONTAINER_ID":/go/src/cache-app/$plugin.so ./docker-build/$plugin.so

# Stop the container (it'll be removed automatically once stopped, as we used `--rm`)
docker stop "$CONTAINER_ID"

```

Dockerfile
```
FROM rwynn/monstache-builder-cache-rel3:1.0.6

WORKDIR /go/src/cache-app

COPY . .

ARG PLUGIN

RUN go build -buildmode=plugin -o $PLUGIN.so $PLUGIN.go

```

**Comment by rwynn** [comment]
@BrunoPereira I've just released a new version of monstache and updated the documentation around this.  You can rebuild your plugin after a git pull.  You will also maybe want to update your docker binary to a version that supports multi-stage builds.  Otherwise, you may need to make some tweaks in the Dockerfile.

**Comment by BrunoPereira** [comment]
Hi,
Sorry, lately I didn't had time to test it.... only did that today.

Regarding the line "FROM rwynn/monstache-builder-cache-rel3:1.0.6 AS build-app" producing the "invalid reference format", I still get that error, I "fixe it" by removing the tag

My docker version is earlier than yours, so probably it....
Docker version 17.03.2-ce, build f5ec1e2

Regarding the error when running the plugin, you fixed it.
I used the latest version (with your fix) and it worked great.

Tnx
