### ISSUE TITLE
index ordering issue with elastic max-conns greater than 1

### ISSUE THREAD

**Issue by rwynn** [rwynn/monstache#37]
If the bulk indexer is configured with more than 1 connection to Elasticsearch via `elasticsearch-max-conns` (the default is 10), it is currently possible for an insert followed quickly by an update to the same document to be applied out of order since the operations may end up in different bulk indexing requests (separate connections).  This results in a discrepancy between what is in MongoDB and what is in Elasticsearch until the document is updated again or a full sync is performed via direct reads.  

To fix this and retain the ability to set max-conns greater than 1 for performance, we can use the MongoDB timestamp as an Elasticsearch document version number such that the old data is rejected at indexing time if newer data already exists in Elasticsearch.

This will also require changes in gtm to the how timestamps are put on document read directly from collections (the direct-read feature).  Since we don't have an oplog entry for direct reads we should produce a timestamp with the time that the value was read out of the collection.  This is to ensure that these reads are possibly rejected during indexing in the case that a document is updated, pulled from the oplog, and synced between the time a direct read occurs and when it is indexed into Elasticsearch.

**Comment by rwynn** [comment]
@battle-mage I've just now published a new release which hopefully should fix this issue.

**Comment by battle-mage** [comment]
Thank you for fast reaction!
I did not test the code yet, but when I'm looking at changes - I see that you use only timestamp itself. As we noticed - mongo uses timestamp accurate to 1 second, but if we use this timestamp - issue with document updated twice in a period of 1 second still exists.
As I noticed - mongo stores timestamps in format Timestamp(X, Y), where X - is the timestamp and Y - is the coutner for this exact timestamp, so if there will be 2 changes - they will have
Timestamp(X, 1)
Timestamp(Y, 2)
Shouldn't we also use this Y number for versioning?

**Comment by rwynn** [comment]
@battle-mage I think the [MongoDB Timestamp](https://docs.mongodb.com/manual/reference/bson-types/#timestamps) already accounts for the counter within a second in the ordinal bits.  Unless I am missing something, if two events where recorded to the oplog within the same second, they would both have the same `time_t` component of the timestamp, but the 2nd event would have a higher `ordinal` component than the 1st, and thus a higher value of the entire 64 bit timestamp.

**Comment by battle-mage** [comment]
We've been testing the last changes with some stress testing and looks like everything syncs just as it should. Versioning works fine :) Think we can close this issue, thanks for your work!

**Comment by rwynn** [comment]
Thanks for bringing up this issue as well as the lack of support for sharded clusters.  That was a pretty significant gap that has now been filled.  I appreciate your contributions!
