### ISSUE TITLE
reconnect to mongos and elasticsearch

### ISSUE THREAD

**Issue by 3JIou** [rwynn/monstache#39]
looks like if service lose connect to mongos (sharding cluster) it's wan't restore it
`ERROR 2018/01/29 20:39:04 Unable to save timestamp: Closed explicitly`
`ERROR 2018/01/29 20:39:04 Closed explicitly`
but I can connect to mongos

**Comment by rwynn** [comment]
hi thanks for reporting this.  do you happen to use plugins either javascript or golang?  Usually, when I kill the server and try to access it I get the error, io.EOF, which prints as "EOF".   I can try to detect these scenarios and refresh the connection.  However, this looks different in that the error is "Closed Explicitly" which sounds to me like maybe the use of a plugin is involved in the root cause.  I think somewhere session.Close() might be getting called.  I should be copying the session when it goes into "user code" so that calling Close on it does not close the main connection.

**Comment by 3JIou** [comment]
yes, i get the error "EOF", sometimes.

**Comment by 3JIou** [comment]
one more strange thing, if I start monstache with parameters "verbose", I got see this:
```json
"Workers": [
{
"Queued": 1000,
"LastDuration": 1513000000
},
{
"Queued": 1000,
"LastDuration": 492000000
},
{
"Queued": 0,
"LastDuration": 720000000
},
{
"Queued": 0,
"LastDuration": 889000000
},
{
"Queued": 0,
"LastDuration": 635000000
},
{
"Queued": 0,
"LastDuration": 1184000000
},
{
"Queued": 245,
"LastDuration": 213000000
},
{
"Queued": 1000,
"LastDuration": 134000000
},
{
"Queued": 1000,
"LastDuration": 1874000000
},
{
"Queued": 1000,
"LastDuration": 1666000000
}
]
```

and moustache will be stopping, but if I press any key:
```json
"Workers": [
{
"Queued": 0,
"LastDuration": 1000000
},
{
"Queued": 18,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
},
{
"Queued": 0,
"LastDuration": 0
}
]
```

**Comment by rwynn** [comment]
The workers output looks like the stats which are described [here](https://github.com/olivere/elastic/blob/release-branch.v5/bulk_processor.go#L183)

As far as the connection loss, can you please do a fresh install from latest in master using

```
go get -u github.com/rwynn/gtm
go get -u github.com/rwynn/monstache
```

I've made some changes just now which may help with reconnection.

**Comment by 3JIou** [comment]
I have one more questions about logs:
`ERROR 2018/01/30 11:47:24 TypeError`
what's is mean?

**Comment by rwynn** [comment]
Regarding the `TypeError` message, I have not seen that before.  And the message doesn't give us a lot of context to go on.   Did you configure custom javascript or go code?

Regarding stats, Failed: 2901 means that 2,901 requests to Elasticsearch have failed from the current Monstache process.  These would be bulk requests so each request may contain more than one document for indexing.  The stats reset to 0 when you restart the Monstache service.

**Comment by 3JIou** [comment]
Yes, I use custom javascript. One more question, sorry, but I have use this service in my project and I need to know - how to get more info about TypeError?

**Comment by rwynn** [comment]
If you remove the Javascript do you still get the `TypeError`?  If you only get the error with the javascript, can you post it here so that maybe I can determine the problem?

I think a TypeError would occur when, for example, you called a method on null, or called a method that doesn't exist.  e.g. null.anything() or "abc".doSomething().   
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError

Also, I discovered more about the flood of error messages in the logs when Elasticsearch is stopped.  I created a PR for the golang elastic client library for this issue.  https://github.com/olivere/elastic/pull/698

**Comment by cmosgh** [comment]
hi @rwynn 
I sometimes get the same issue and I see @olivere already merged the PR.
Any chance you can build a new version with that included
I would then update the docker image also

**Comment by olivere** [comment]
@cmosgh No, I didn't? I think I need to look into the details first.

**Comment by cmosgh** [comment]
@olivere
Thought since tests were passed you did. My bad

**Comment by 3JIou** [comment]
thank you for your help

**Comment by rwynn** [comment]
@cmosgh I just pushed a new 3.6.0 release that you can use to update the docker image.  This includes some fixes for lost connections while we wait for the elastic PR to be reviewed.  I switched the import over to my fork temporarily.

**Comment by rwynn** [comment]
Reconnecting to MongoDB and Elasticsearch has been fixed in 3.6.2.  Thanks!

**Comment by benan789** [comment]
Does this fix also apply to direct read? I've been getting

> Error performing direct reads of collections: read tcp 172.31.11.220:38794->35.164.165.141:27017: i/o timeout

and syncing just stops completely.

**Comment by rwynn** [comment]
The logic is here https://github.com/rwynn/gtm/blob/master/gtm.go. I don’t think that error is handled. Bunch of other io errors are though. I need to find where that error is defined in the standard library. Couldn’t find it here with the others https://golang.org/pkg/io/#pkg-variables

**Comment by rwynn** [comment]
@benan789 can you please re-download the latest release (3.x for ES2-5, 4.X for ES6+) of Monstache and try this again?  I have reworked the tailing library that Monstache uses, rebuilt the binaries, and run some tests.  I updated this library do a periodic ping after ANY type of error encountered (these are reads so there really isn't much that can happen besides broken connections).  Hopefully, it won't exit early from now on.

**Comment by benan789** [comment]
Still having issue doing a full sync of about 10mil documents, suspecting the meta collection.

#44

**Comment by rwynn** [comment]
What is the error from the log with the latest monstache code?

**Comment by benan789** [comment]
It's the same error actually. Maybe it didn't stop completely but just didn't update in a while and I thought it stopped lol.
